// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";
import useGlobalStore from "@/pages/globalStore";

/**
 * Get account info
 */
export async function AccountControllerFindOne(
  params: Paths.AccountControllerFindOne.BodyParameters | any,
): Promise<Paths.AccountControllerFindOne.Responses> {
  // /v1/accounts
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/accounts`, {
    method: "GET",
    params: params,
  });
}

/**
 * Get charge order
 */
export async function AccountControllerGetChargeOrder(
  params: Paths.AccountControllerGetChargeOrder.BodyParameters | any,
): Promise<Paths.AccountControllerGetChargeOrder.Responses> {
  // /v1/accounts/charge-order/{id}
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/accounts/charge-order/${_params.id}`, {
    method: "GET",
    params: params,
  });
}

/**
 * Create charge order
 */
export async function AccountControllerCharge(
  params: Definitions.CreateChargeOrderDto | any,
): Promise<Paths.AccountControllerCharge.Responses> {
  // /v1/accounts/charge-order
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/accounts/charge-order`, {
    method: "POST",
    data: params,
  });
}

/**
 *
 */
export async function AccountControllerWechatNotify(
  params: Paths.AccountControllerWechatNotify.BodyParameters | any,
): Promise<Paths.AccountControllerWechatNotify.Responses> {
  // /v1/accounts/payment/wechat-notify
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/accounts/payment/wechat-notify`, {
    method: "POST",
    data: params,
  });
}
