// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";
import useGlobalStore from "@/pages/globalStore";

/**
 * Get billings of an application
 */
export async function BillingControllerFindAll(
  params: Paths.BillingControllerFindAll.BodyParameters,
): Promise<{
  error: string;
  data: Paths.BillingControllerFindAll.Responses;
}> {
  // /v1/billings
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/billings`, {
    method: "GET",
    params: params,
  });
}
