// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";
import useGlobalStore from "@/pages/globalStore";

/**
 * Get user token by auth code
 */
export async function AuthControllerCode2token(
  params: Paths.AuthControllerCode2token.BodyParameters | any,
): Promise<Paths.AuthControllerCode2token.Responses> {
  // /v1/code2token
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/code2token`, {
    method: "GET",
    params: params,
  });
}
