// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";
import useGlobalStore from "@/pages/globalStore";

/**
 * Get user token by PAT
 */
export async function AuthControllerPat2token(
  params: Definitions.Pat2TokenDto | any,
): Promise<Paths.AuthControllerPat2token.Responses> {
  // /v1/pat2token
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/pat2token`, {
    method: "POST",
    data: params,
  });
}
