// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Get current user profile
 */
export async function AuthControllerGetPATs(
  params: any,
): Promise<Paths.AuthControllerGetProfile.Responses> {
  // /v1/profile
  return request(`/v1/pats`, {
    method: "GET",
    params: params,
  });
}

export async function AuthControllerPATsRemove(
  params: any,
): Promise<Paths.AuthControllerGetProfile.Responses> {
  // /v1/profile
  let _params: { [key: string]: any } = {
    appid: localStorage.getItem("app"),
    ...params,
  };
  return request(`/v1/pats/${_params.id}`, {
    method: "DELETE",
    data: params,
  });
}

export async function AuthControllerPATsCreate(
  params: any,
): Promise<Paths.AuthControllerGetProfile.Responses> {
  // /v1/profile
  return request(`/v1/pats`, {
    method: "POST",
    data: params,
  });
}
