// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";
import useGlobalStore from "@/pages/globalStore";

/**
 * Get current user profile
 */
export async function AuthControllerGetProfile(
  params: Paths.AuthControllerGetProfile.BodyParameters | any,
): Promise<Paths.AuthControllerGetProfile.Responses> {
  // /v1/profile
  let _params: { [key: string]: any } = {
    appid: useGlobalStore.getState().currentApp?.appid || "",
    ...params,
  };
  return request(`/v1/profile`, {
    method: "GET",
    params: params,
  });
}
