// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Get region list
 */
export async function AppControllerGetRegions(
  params: Paths.AppControllerGetRegions.BodyParameters | any,
): Promise<Paths.AppControllerGetRegions.Responses> {
  // /v1/regions
  let _params: { [key: string]: any } = {
    appid: localStorage.getItem("app"),
    ...params,
  };
  return request(`/v1/regions`, {
    method: "GET",
    params: params,
  });
}
