///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Redirect to register page
 */
export async function AuthControllerGetSignupUrl(
  params: Paths.AuthControllerGetSignupUrl.BodyParameters | any,
): Promise<Paths.AuthControllerGetSignupUrl.Responses> {
  // /v1/register
  let _params: { [key: string]: any } = {
    appid: localStorage.getItem("app"),
    ...params,
  };
  return request(`/v1/register`, {
    method: "GET",
    params: params,
  });
}
