import { NextApiRequest, NextApiResponse } from "next";

import { JsonResp } from "./response";

export default async function handler(req: NextApiRequest, resp: NextApiResponse) {
  JsonResp(
    {
      list: [
        {
          _id: "63652b30bf06cc58ee91a18e",
          requestId: "779f2929f7e2ecab2f86513a1ec012bf",
          method: "POST",
          func_id: "62da6670583927a711b311e3",
          func_name: "admin-edit__SAj9WsnP",
          logs: [],
          time_usage: 1.954,
          created_by: null,
          data: {
            code: "401",
            error: "未授权访问xx  nn  x",
          },
          error: null,
          debug: true,
          created_at: "2022-11-04T15:09:36.478Z",
        },
        {
          _id: "63652b2fbf06cc58ee91a18d",
          requestId: "6fa33953b7a56ef66b3899abf1d2758f",
          method: "POST",
          func_id: "62da6670583927a711b311e3",
          func_name: "admin-edit__SAj9WsnP",
          logs: [],
          time_usage: 4.088,
          created_by: null,
          data: {
            code: "401",
            error: "未授权访问xx  nn  x",
          },
          error: null,
          debug: true,
          created_at: "2022-11-04T15:09:35.467Z",
        },
        {
          _id: "63652b2cbf06cc58ee91a18c",
          requestId: "ebcbff9c8f8489a7384573e3d1556ea4",
          method: "POST",
          func_id: "62da6670583927a711b311e3",
          func_name: "admin-edit__SAj9WsnP",
          logs: [],
          time_usage: 1.846,
          created_by: null,
          data: {
            code: "401",
            error: "未授权访问xx  nn  x",
          },
          error: null,
          debug: true,
          created_at: "2022-11-04T15:09:32.256Z",
        },
        {
          _id: "63652b20bf06cc58ee91a18b",
          requestId: "78d5937d362fca6d96692f0758bd6b22",
          method: "POST",
          func_id: "62da6670583927a711b311e2",
          func_name: "admin-create__5YAAoenl",
          logs: [],
          time_usage: 2.378,
          created_by: null,
          data: "Unauthorisszssed",
          error: null,
          debug: true,
          created_at: "2022-11-04T15:09:20.015Z",
        },
        {
          _id: "6364f231bf06cc58ee91a18a",
          requestId: "trigger_613a347c1ce6a2f7b5d49c16",
          method: "trigger",
          func_id: "62da1bdb583927a711b311b8",
          func_name: "initializer",
          logs: [
            "invoked by trigger: 监听应用启动就绪事件 (613a347c1ce6a2f7b5d49c16)",
            "[2022/11/04 11:06:24] - 初始化 RBAC",
            "[2022/11/04 11:06:24] - 初始化应用集合索引",
            "[2022/11/04 11:06:24] - 初始化 shared_utils",
            "[2022/11/04 11:06:25] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12) {\n  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',\n  config: {\n    url: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    headers: {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/0.21.4'\n    },\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    adapter: [Function: httpAdapter],\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    validateStatus: [Function: validateStatus],\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    method: 'get',\n    data: undefined\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      constructed: true,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false,\n      closeEmitted: false,\n      [Symbol(kOnFinished)]: []\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError]\n    },\n    _eventsCount: 2,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: 10485760,\n      protocol: 'https:',\n      path: '/sys_region.json',\n      method: 'GET',\n      headers: [Object],\n      agent: undefined,\n      agents: [Object],\n      auth: undefined,\n      hostname: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      port: null,\n      nativeProtocols: [Object],\n      pathname: '/sys_region.json'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 0,\n    _requestBodyBuffers: [],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: true,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: true,\n      socket: [TLSSocket],\n      _header: 'GET /sys_region.json HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/0.21.4\\r\\n' +\n        'Host: a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/sys_region.json',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      protocol: 'https:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype],\n      [Symbol(kUniqueHeaders)]: null\n    },\n    _currentUrl: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    [Symbol(kCapture)]: false\n  },\n  response: undefined,\n  isAxiosError: true,\n  toJSON: [Function: toJSON]\n}",
          ],
          time_usage: 579.162,
          created_by: "trigger_613a347c1ce6a2f7b5d49c16",
          trigger_id: "613a347c1ce6a2f7b5d49c16",
          created_at: "2022-11-04T11:06:25.362Z",
        },
        {
          _id: "6364f231bf06cc58ee91a189",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b7",
          func_name: "init-sys-region",
          logs: [
            "[2022/11/04 11:06:25] - self-signed certificate",
            "[2022/11/04 11:06:25] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)",
          ],
          time_usage: 395.612,
          data: null,
          error: "Error: self-signed certificate",
          created_at: "2022-11-04T11:06:25.349Z",
        },
        {
          _id: "6364f231bf06cc58ee91a188",
          requestId: "trigger_613a347c1ce6a2f7b5d49c16",
          method: "trigger",
          func_id: "62da6670583927a711b311ed",
          func_name: "initializer__DWDxT0rt",
          logs: [
            "invoked by trigger: 监听应用启动就绪事件 (613a347c1ce6a2f7b5d49c16)",
            "[2022/11/04 11:06:24] - 初始化 RBAC",
            "[2022/11/04 11:06:24] - 初始化应用集合索引",
            "[2022/11/04 11:06:24] - 初始化 shared_utils",
            "[2022/11/04 11:06:25] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12) {\n  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',\n  config: {\n    url: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    headers: {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/0.21.4'\n    },\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    adapter: [Function: httpAdapter],\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    validateStatus: [Function: validateStatus],\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    method: 'get',\n    data: undefined\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      constructed: true,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false,\n      closeEmitted: false,\n      [Symbol(kOnFinished)]: []\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError]\n    },\n    _eventsCount: 2,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: 10485760,\n      protocol: 'https:',\n      path: '/sys_region.json',\n      method: 'GET',\n      headers: [Object],\n      agent: undefined,\n      agents: [Object],\n      auth: undefined,\n      hostname: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      port: null,\n      nativeProtocols: [Object],\n      pathname: '/sys_region.json'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 0,\n    _requestBodyBuffers: [],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: true,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: true,\n      socket: [TLSSocket],\n      _header: 'GET /sys_region.json HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/0.21.4\\r\\n' +\n        'Host: a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/sys_region.json',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      protocol: 'https:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype],\n      [Symbol(kUniqueHeaders)]: null\n    },\n    _currentUrl: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    [Symbol(kCapture)]: false\n  },\n  response: undefined,\n  isAxiosError: true,\n  toJSON: [Function: toJSON]\n}",
          ],
          time_usage: 524.618,
          created_by: "trigger_613a347c1ce6a2f7b5d49c16",
          trigger_id: "613a347c1ce6a2f7b5d49c16",
          created_at: "2022-11-04T11:06:25.299Z",
        },
        {
          _id: "6364f231bf06cc58ee91a187",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b7",
          func_name: "init-sys-region",
          logs: [
            "[2022/11/04 11:06:25] - self-signed certificate",
            "[2022/11/04 11:06:25] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)",
          ],
          time_usage: 328.811,
          data: null,
          error: "Error: self-signed certificate",
          created_at: "2022-11-04T11:06:25.285Z",
        },
        {
          _id: "6364f230bf06cc58ee91a186",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b5",
          func_name: "init_shared_utils",
          logs: [],
          time_usage: 1.295,
          data: "ok",
          error: null,
          created_at: "2022-11-04T11:06:24.944Z",
        },
        {
          _id: "6364f230bf06cc58ee91a185",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b5",
          func_name: "init_shared_utils",
          logs: [],
          time_usage: 1.405,
          data: "ok",
          error: null,
          created_at: "2022-11-04T11:06:24.942Z",
        },
        {
          _id: "6364f230bf06cc58ee91a184",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b6",
          func_name: "init-app-rbac",
          logs: [
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - admin already exists",
          ],
          time_usage: 121.948,
          data: "ok",
          error: null,
          created_at: "2022-11-04T11:06:24.913Z",
        },
        {
          _id: "6364f230bf06cc58ee91a183",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b6",
          func_name: "init-app-rbac",
          logs: [
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - permissions already exists",
            "[2022/11/04 11:06:24] - admin already exists",
          ],
          time_usage: 116.604,
          data: "ok",
          error: null,
          created_at: "2022-11-04T11:06:24.912Z",
        },
        {
          _id: "6364e86c29faf308a349aaf5",
          requestId: "394ec89afd8a52ded08f09a6aa426e82",
          method: "POST",
          func_id: "62da1bdb583927a711b311b3",
          func_name: "app-login-password",
          logs: [],
          time_usage: 5.423,
          created_by: null,
          data: {
            code: "INVALID_PARAM",
            error: "用户名或密码不正确",
          },
          error: null,
          debug: true,
          created_at: "2022-11-04T10:24:44.430Z",
        },
        {
          _id: "6362a66429faf308a349aaf4",
          requestId: "trigger_613a347c1ce6a2f7b5d49c16",
          method: "trigger",
          func_id: "62da1bdb583927a711b311b8",
          func_name: "initializer",
          logs: [
            "invoked by trigger: 监听应用启动就绪事件 (613a347c1ce6a2f7b5d49c16)",
            "[2022/11/02 17:18:26] - 初始化 RBAC",
            "[2022/11/02 17:18:26] - 初始化应用集合索引",
            "[2022/11/02 17:18:26] - 初始化 shared_utils",
            "[2022/11/02 17:18:28] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12) {\n  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',\n  config: {\n    url: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    headers: {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/0.21.4'\n    },\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    adapter: [Function: httpAdapter],\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    validateStatus: [Function: validateStatus],\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    method: 'get',\n    data: undefined\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      constructed: true,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false,\n      closeEmitted: false,\n      [Symbol(kOnFinished)]: []\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError]\n    },\n    _eventsCount: 2,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: 10485760,\n      protocol: 'https:',\n      path: '/sys_region.json',\n      method: 'GET',\n      headers: [Object],\n      agent: undefined,\n      agents: [Object],\n      auth: undefined,\n      hostname: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      port: null,\n      nativeProtocols: [Object],\n      pathname: '/sys_region.json'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 0,\n    _requestBodyBuffers: [],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: true,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: true,\n      socket: [TLSSocket],\n      _header: 'GET /sys_region.json HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/0.21.4\\r\\n' +\n        'Host: a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/sys_region.json',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      protocol: 'https:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype],\n      [Symbol(kUniqueHeaders)]: null\n    },\n    _currentUrl: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    [Symbol(kCapture)]: false\n  },\n  response: undefined,\n  isAxiosError: true,\n  toJSON: [Function: toJSON]\n}",
          ],
          time_usage: 2519.372,
          created_by: "trigger_613a347c1ce6a2f7b5d49c16",
          trigger_id: "613a347c1ce6a2f7b5d49c16",
          created_at: "2022-11-02T17:18:28.545Z",
        },
        {
          _id: "6362a66429faf308a349aaf3",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b7",
          func_name: "init-sys-region",
          logs: [
            "[2022/11/02 17:18:28] - self-signed certificate",
            "[2022/11/02 17:18:28] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)",
          ],
          time_usage: 2124.788,
          data: null,
          error: "Error: self-signed certificate",
          created_at: "2022-11-02T17:18:28.534Z",
        },
        {
          _id: "6362a66229faf308a349aaf2",
          requestId: "trigger_613a347c1ce6a2f7b5d49c16",
          method: "trigger",
          func_id: "62da6670583927a711b311ed",
          func_name: "initializer__DWDxT0rt",
          logs: [
            "invoked by trigger: 监听应用启动就绪事件 (613a347c1ce6a2f7b5d49c16)",
            "[2022/11/02 17:18:26] - 初始化 RBAC",
            "[2022/11/02 17:18:26] - 初始化应用集合索引",
            "[2022/11/02 17:18:26] - 初始化 shared_utils",
            "[2022/11/02 17:18:26] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12) {\n  code: 'DEPTH_ZERO_SELF_SIGNED_CERT',\n  config: {\n    url: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    headers: {\n      Accept: 'application/json, text/plain, */*',\n      'User-Agent': 'axios/0.21.4'\n    },\n    transformRequest: [ [Function: transformRequest] ],\n    transformResponse: [ [Function: transformResponse] ],\n    timeout: 0,\n    adapter: [Function: httpAdapter],\n    xsrfCookieName: 'XSRF-TOKEN',\n    xsrfHeaderName: 'X-XSRF-TOKEN',\n    maxContentLength: -1,\n    maxBodyLength: -1,\n    validateStatus: [Function: validateStatus],\n    transitional: {\n      silentJSONParsing: true,\n      forcedJSONParsing: true,\n      clarifyTimeoutError: false\n    },\n    method: 'get',\n    data: undefined\n  },\n  request: <ref *1> Writable {\n    _writableState: WritableState {\n      objectMode: false,\n      highWaterMark: 16384,\n      finalCalled: false,\n      needDrain: false,\n      ending: false,\n      ended: false,\n      finished: false,\n      destroyed: false,\n      decodeStrings: true,\n      defaultEncoding: 'utf8',\n      length: 0,\n      writing: false,\n      corked: 0,\n      sync: true,\n      bufferProcessing: false,\n      onwrite: [Function: bound onwrite],\n      writecb: null,\n      writelen: 0,\n      afterWriteTickInfo: null,\n      buffered: [],\n      bufferedIndex: 0,\n      allBuffers: true,\n      allNoop: true,\n      pendingcb: 0,\n      constructed: true,\n      prefinished: false,\n      errorEmitted: false,\n      emitClose: true,\n      autoDestroy: true,\n      errored: null,\n      closed: false,\n      closeEmitted: false,\n      [Symbol(kOnFinished)]: []\n    },\n    _events: [Object: null prototype] {\n      response: [Function: handleResponse],\n      error: [Function: handleRequestError]\n    },\n    _eventsCount: 2,\n    _maxListeners: undefined,\n    _options: {\n      maxRedirects: 21,\n      maxBodyLength: 10485760,\n      protocol: 'https:',\n      path: '/sys_region.json',\n      method: 'GET',\n      headers: [Object],\n      agent: undefined,\n      agents: [Object],\n      auth: undefined,\n      hostname: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      port: null,\n      nativeProtocols: [Object],\n      pathname: '/sys_region.json'\n    },\n    _ended: true,\n    _ending: true,\n    _redirectCount: 0,\n    _redirects: [],\n    _requestBodyLength: 0,\n    _requestBodyBuffers: [],\n    _onNativeResponse: [Function (anonymous)],\n    _currentRequest: ClientRequest {\n      _events: [Object: null prototype],\n      _eventsCount: 7,\n      _maxListeners: undefined,\n      outputData: [],\n      outputSize: 0,\n      writable: true,\n      destroyed: true,\n      _last: true,\n      chunkedEncoding: false,\n      shouldKeepAlive: false,\n      maxRequestsOnConnectionReached: false,\n      _defaultKeepAlive: true,\n      useChunkedEncodingByDefault: false,\n      sendDate: false,\n      _removedConnection: false,\n      _removedContLen: false,\n      _removedTE: false,\n      _contentLength: 0,\n      _hasBody: true,\n      _trailer: '',\n      finished: true,\n      _headerSent: true,\n      _closed: true,\n      socket: [TLSSocket],\n      _header: 'GET /sys_region.json HTTP/1.1\\r\\n' +\n        'Accept: application/json, text/plain, */*\\r\\n' +\n        'User-Agent: axios/0.21.4\\r\\n' +\n        'Host: a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com\\r\\n' +\n        'Connection: close\\r\\n' +\n        '\\r\\n',\n      _keepAliveTimeout: 0,\n      _onPendingData: [Function: nop],\n      agent: [Agent],\n      socketPath: undefined,\n      method: 'GET',\n      maxHeaderSize: undefined,\n      insecureHTTPParser: undefined,\n      path: '/sys_region.json',\n      _ended: false,\n      res: null,\n      aborted: false,\n      timeoutCb: null,\n      upgradeOrConnect: false,\n      parser: null,\n      maxHeadersCount: null,\n      reusedSocket: false,\n      host: 'a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com',\n      protocol: 'https:',\n      _redirectable: [Circular *1],\n      [Symbol(kCapture)]: false,\n      [Symbol(kNeedDrain)]: false,\n      [Symbol(corked)]: 0,\n      [Symbol(kOutHeaders)]: [Object: null prototype],\n      [Symbol(kUniqueHeaders)]: null\n    },\n    _currentUrl: 'https://a5bec5b2-ebd0-4803-b29b-0a1766aa7edf_data.fs.lafyun.com/sys_region.json',\n    [Symbol(kCapture)]: false\n  },\n  response: undefined,\n  isAxiosError: true,\n  toJSON: [Function: toJSON]\n}",
          ],
          time_usage: 672.082,
          created_by: "trigger_613a347c1ce6a2f7b5d49c16",
          trigger_id: "613a347c1ce6a2f7b5d49c16",
          created_at: "2022-11-02T17:18:26.692Z",
        },
        {
          _id: "6362a66229faf308a349aaf1",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b7",
          func_name: "init-sys-region",
          logs: [
            "[2022/11/02 17:18:26] - self-signed certificate",
            "[2022/11/02 17:18:26] - Error: self-signed certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1538:34)\n    at TLSSocket.emit (node:events:513:28)\n    at TLSSocket._finishInit (node:_tls_wrap:952:8)\n    at ssl.onhandshakedone (node:_tls_wrap:733:12)",
          ],
          time_usage: 449.014,
          data: null,
          error: "Error: self-signed certificate",
          created_at: "2022-11-02T17:18:26.678Z",
        },
        {
          _id: "6362a66229faf308a349aaf0",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b5",
          func_name: "init_shared_utils",
          logs: [],
          time_usage: 1.33,
          data: "ok",
          error: null,
          created_at: "2022-11-02T17:18:26.222Z",
        },
        {
          _id: "6362a66229faf308a349aaef",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b5",
          func_name: "init_shared_utils",
          logs: [],
          time_usage: 1.589,
          data: "ok",
          error: null,
          created_at: "2022-11-02T17:18:26.219Z",
        },
        {
          _id: "6362a66229faf308a349aaee",
          requestId: "invoke",
          method: "call",
          func_id: "62da1bdb583927a711b311b6",
          func_name: "init-app-rbac",
          logs: [
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - permissions already exists",
            "[2022/11/02 17:18:26] - admin already exists",
          ],
          time_usage: 124.608,
          data: "ok",
          error: null,
          created_at: "2022-11-02T17:18:26.206Z",
        },
      ],
      total: 25,
      limit: 20,
      page: 1,
    },
    resp,
  );
}
