///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Create a new application
 */
export async function ApplicationsControllerCreate(
  params: Definitions.CreateApplicationDto,
  extra?: { [key: string]: any },
): Promise<Paths.ApplicationsControllerCreate.Responses> {
  return request("/v1/applications", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 * Get an application by appid
 */
export async function ApplicationsControllerFindOne(
  params: Paths.ApplicationsControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.ApplicationsControllerFindOne.Responses> {
  return request("/v1/applications/{appid}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
