///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 *
 */
export async function FunctionsControllerCreate(
  params: Definitions.CreateFunctionDto,
  extra?: { [key: string]: any },
): Promise<Paths.FunctionsControllerCreate.Responses> {
  return request("/v1/apps/{appid}/functions", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function FunctionsControllerFindOne(
  params: Paths.FunctionsControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.FunctionsControllerFindOne.Responses> {
  return request("/v1/apps/{appid}/functions/{name}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function FunctionsControllerUpdate(
  params: Definitions.UpdateFunctionDto,
  extra?: { [key: string]: any },
): Promise<Paths.FunctionsControllerUpdate.Responses> {
  return request("/v1/apps/{appid}/functions/{id}", {
    method: "PATCH",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function PoliciesControllerCreate(
  params: Definitions.CreatePolicyDto,
  extra?: { [key: string]: any },
): Promise<Paths.PoliciesControllerCreate.Responses> {
  return request("/v1/apps/{appid}/policies", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function PoliciesControllerFindOne(
  params: Paths.PoliciesControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.PoliciesControllerFindOne.Responses> {
  return request("/v1/apps/{appid}/policies/{id}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function BucketsControllerCreate(
  params: Definitions.CreateBucketDto,
  extra?: { [key: string]: any },
): Promise<Paths.BucketsControllerCreate.Responses> {
  return request("/v1/apps/{appid}/buckets", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function BucketsControllerFindOne(
  params: Paths.BucketsControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.BucketsControllerFindOne.Responses> {
  return request("/v1/apps/{appid}/buckets/{name}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function BucketsControllerUpdate(
  params: Definitions.UpdateBucketDto,
  extra?: { [key: string]: any },
): Promise<Paths.BucketsControllerUpdate.Responses> {
  return request("/v1/apps/{appid}/buckets/{id}", {
    method: "PATCH",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function WebsitesControllerCreate(
  params: Definitions.CreateWebsiteDto,
  extra?: { [key: string]: any },
): Promise<Paths.WebsitesControllerCreate.Responses> {
  return request("/v1/apps/{appid}/websites", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function WebsitesControllerFindOne(
  params: Paths.WebsitesControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.WebsitesControllerFindOne.Responses> {
  return request("/v1/apps/{appid}/websites/{id}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function CollectionsControllerCreate(
  params: Definitions.CreateCollectionDto,
  extra?: { [key: string]: any },
): Promise<Paths.CollectionsControllerCreate.Responses> {
  return request("/v1/apps/{appid}/collections", {
    method: "POST",
    data: params,
    ...(extra || {}),
  });
}

/**
 *
 */
export async function CollectionsControllerFindOne(
  params: Paths.CollectionsControllerFindOne.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.CollectionsControllerFindOne.Responses> {
  return request("/v1/apps/{appid}/collections/{name}", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
