///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 *
 */
export async function AppControllerCode2token(
  params: Paths.AppControllerCode2token.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.AppControllerCode2token.Responses> {
  return request("/v1/code2token", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
