///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Redirect to login page
 */
export async function AppControllerGetSigninUrl(
  params: Paths.AppControllerGetSigninUrl.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.AppControllerGetSigninUrl.Responses> {
  return request("/v1/login", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
