///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Redirect to register page
 */
export async function AuthControllerGetSignupUrl(
  params: Paths.AuthControllerGetSignupUrl.BodyParameters | any,
  extra?: { [key: string]: any },
): Promise<Paths.AuthControllerGetSignupUrl.Responses> {
  // /v1/register
  return request(`/v1/register`, {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
