///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 *
 */
export async function AppControllerGetSignupUrl(
  params: Paths.AppControllerGetSignupUrl.BodyParameters,
  extra?: { [key: string]: any },
): Promise<Paths.AppControllerGetSignupUrl.Responses> {
  return request("/v1/register", {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
