///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from "@/utils/request";

/**
 * Get application runtime list
 */
export async function SpecsControllerGetRuntimes(
  params: Paths.SpecsControllerGetRuntimes.BodyParameters | any,
  extra?: { [key: string]: any },
): Promise<Paths.SpecsControllerGetRuntimes.Responses> {
  // /v1/runtimes
  return request(`/v1/runtimes`, {
    method: "GET",
    params: params,
    ...(extra || {}),
  });
}
